CREATE DATABASE HospitalSystem

USE HospitalSystem
GO

CREATE TABLE Patients
(
	PatientID		INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName		VARCHAR(100) NOT NULL,
	LastName		VARCHAR(100) NOT NULL,
	DateOfBirth		DATE NOT NULL,
	CHECK (DateOfBirth > '1900-01-01')
)

CREATE TABLE Doctors
(
	DoctorID		INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName		VARCHAR(100) NOT NULL,
	LastName		VARCHAR(100) NOT NULL,
	Speciality		VARCHAR(100) NOT NULL
)

CREATE TABLE Rooms
(
	RoomID			INT PRIMARY KEY IDENTITY NOT NULL,
	RoomNr			INT UNIQUE NOT NULL,
	RoomType		VARCHAR(100) NOT NULL
)

CREATE TABLE Admission
(
	AdmissionID		INT PRIMARY KEY IDENTITY NOT NULL,
	PatientID		INT REFERENCES Patients(PatientID) NOT NULL,
	RoomID			INT REFERENCES Rooms(roomID) NOT NULL,
	AdmissionTime	DATETIME NOT NULL
)

CREATE TABLE Appointments
(
	AppointmentID	INT PRIMARY KEY IDENTITY NOT NULL,
	PatientID		INT REFERENCES Patients(PatientID) NOT NULL,
	DoctorID		INT REFERENCES Doctors(DoctorID) NOT NULL,
	RoomID			INT REFERENCES Rooms(RoomID) NOT NULL,
	AppointmentTime	DATETIME NOT NULL
)



